databaseChangeLog:
  - changeSet:
      id: create_point_configurations_table
      author: Eduard Le Roux
      changes:
        - createTable:
            tableName: point_configurations
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: request_pkey

              - column:
                  name: outcome
                  type: VARCHAR(50)
                  constraints:
                    nullable: false

              - column:
                  name: points
                  type: INT
                  constraints:
                    nullable: false

              - column:
                  name: updated_at
                  type: DATETIME
                  valueDate: "YYYY-MM-DDThh:mm:ss"
                  constraints:
                    nullable: false

              - column:
                  name: created_at
                  type: DATETIME
                  valueDate: "YYYY-MM-DDThh:mm:ss"
                  constraints:
                    nullable: false
